services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${IMMICH_UPLOAD_LOCATION:-./library}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_HOSTNAME: database
      DB_USERNAME: ${IMMICH_DB_USERNAME:-postgres}
      DB_PASSWORD: ${IMMICH_DB_PASSWORD:-postgres}
      DB_DATABASE_NAME: ${IMMICH_DB_DATABASE_NAME:-immich}
      REDIS_HOSTNAME: redis
      TZ: ${IMMICH_TZ:-America/New_York}
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - immich_network
      - npm_network
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - immich_model_cache:/cache
    environment:
      TZ: ${IMMICH_TZ:-America/New_York}
    restart: unless-stopped
    networks:
      - immich_network
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
    restart: unless-stopped
    networks:
      - immich_network
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD:-postgres}
      POSTGRES_USER: ${IMMICH_DB_USERNAME:-postgres}
      POSTGRES_DB: ${IMMICH_DB_DATABASE_NAME:-immich}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - immich_postgres_data:/var/lib/postgresql/data
    shm_size: 128mb
    restart: unless-stopped
    networks:
      - immich_network

volumes:
  immich_model_cache:
  immich_postgres_data:

networks:
  immich_network:
    name: immich_network
  npm_network:
    name: npm_network
    external: true
